apiVersion: v1
kind: Service
name: hello-http-svc
meta:
  name: hello-http
  labels:
    app: hello-http
spec:
  type: ClusterIP
  selector:
    app: hello-http
  ports:
    - name: http
      port: 80        # Service port
      targetPort: 80  # Container port
      protocol: TCP
